### PR TITLE
Removed Hairline from STAT

### PR DESCRIPTION
**Pull request by RosaWagner**
Corrected config file and designspace for the user value of Hairline to be 1 as per my comment in https://github.com/google/fonts/issues/6703#issuecomment-1721581148

### CODE REVIEW

**Comment by dy** [comment]
Hi Rosalie! I'm afraid this is not fully desirable, as I mentioned before. This would introduce nonlinearity which makes practical use of font harder. To make proper mapping it would need output=0.25 value, which is not supported by designspace. Therefore I am ok with skipping Hairline

**Comment by RosaWagner** [comment]
Ok, we didn't understand each other in that other thread. Then I guess I'll merge the PR https://github.com/google/fonts/pull/6705 with min at 20 ?

**Comment by dy** [comment]
I reduced min to 4 in the latest version, I'd suggest taking that

**Comment by RosaWagner** [comment]
Then you can merge my modification here to the STAT, and I'll reonboard one the fonts are re-built

**Comment by dy** [comment]
Should I include ExtraBlack instance in designfile @RosaWagner?

**Comment by RosaWagner** [comment]
@dy I don't think we accept it since the API doesn't support it. But sometimes we make exception for users who download the font, let me check with my colleague and I'll get back to you tomorrow.

**Pull request merged**
